### ISSUE TITLE
lalinference 2.0.6 master build failed with Segmentation fault

### ISSUE THREAD

**Issue by duncanmmacleod** [conda-forge/lalinference-feedstock#33]
The latest `master` build of this feedstock raised a segmentation fault, I think because of numpy 1.20.0. @conda-forge/core, has that been seen in other projects?

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=271810&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=22690

**Comment by chrisburr** [comment]
Can you try forcing the build to use 1.20 in `host`?

**Comment by duncanmmacleod** [comment]
@chrisburr, AFAICT forcing the build with numpy 1.20.0 **does not** affect the segmentation fault - i.e. the build passes fine, but the segmentation fault still occurs.

**Comment by duncanmmacleod** [comment]
The segmentation fault actually comes from `lal` so I'll move to looking over there instead.
